#!/usr/bin/env bash
# Fails if any dist/ files were added or modified in the PR diff.
# Required env: BASE_SHA (= github.event.pull_request.base.sha)
set -euo pipefail

DIST_FILES=$(git diff --name-only "$BASE_SHA" HEAD | grep -E '(^|/)dist/' || true)
if [ -n "$DIST_FILES" ]; then
  echo "::error::Committed dist/ files detected in this PR:"
  echo "$DIST_FILES" | sed 's/^/  - /'
  echo "dist/ is generated by CI and must not be committed."
  echo "To untrack: git rm -r --cached lib/js/dist/ && git commit"
  exit 1
fi
echo "✅ No committed dist/ files"
