name: 'Build and Package Library'
description: 'Sets up the environment, builds, and packages a target.'
inputs:
  target:
    description: 'Target package (vonage or opentok)'
    required: true
  node_version:
    description: 'Node.js version to use (e.g. 24.x)'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Environment
      uses: ./.github/actions/setup-environment
      with:
        target: ${{ inputs.target }}
        node_version: ${{ inputs.node_version }}

    - name: Build
      shell: bash
      working-directory: lib/js
      run: npm run build

    - name: Package Tarball
      uses: ./.github/actions/package-tarball
      with:
        target: ${{ inputs.target }}
