/**
 * Test environment configuration.
 *
 * Reads credentials.json (generated by setup.js) and exposes:
 * - `credentials` — the session credential sets (primary, faultyLogging, faultyApi)
 * - `apiUrl` — the custom video API host (undefined when using production)
 * - `OT` — a mutable wrapper around the @vonage/client-sdk-video module that allows
 *   Jasmine's spyOn() to replace methods (the real module uses non-writable exports).
 * - `createNetworkTest()` — factory that creates a NetworkTest instance with the
 *   correct apiUrl baked in, so individual tests don't need to repeat the boilerplate.
 *
 * Usage in a spec file:
 *
 *   import { credentials, createNetworkTest, OT } from './testEnv';
 *
 *   const networkTest = createNetworkTest(credentials.primary);
 *   spyOn(OT, 'initSession').and.callFake(...);
 */
import * as OTClient from '@vonage/client-sdk-video';
import credentialsJson from './credentials.json';
import NetworkTest, { NetworkTestOptions } from '../src';
import { SessionCredentials } from '../src/types/session';

// credentials.json is extended by setup.js to include an optional `apiUrl` field.
interface CredentialsFile {
  primary: SessionCredentials;
  faultyLogging: SessionCredentials;
  faultyApi: SessionCredentials;
  apiUrl?: string;
}

const parsed: CredentialsFile = credentialsJson as CredentialsFile;

/** Session credentials generated by test-setup */
export const credentials = {
  primary: parsed.primary,
  faultyLogging: parsed.faultyLogging,
  faultyApi: parsed.faultyApi,
};

/**
 * Custom API URL for non-production environments.
 * Undefined when running against production.
 */
export const apiUrl: string | undefined = parsed.apiUrl;

/**
 * A mutable wrapper around the @vonage/client-sdk-video module.
 *
 * The SDK exports its methods via webpack's Object.defineProperty pattern
 * (enumerable: true, configurable: false, writable: false), which prevents
 * Jasmine's spyOn() from replacing them.
 *
 * We use a Proxy over a plain object (to avoid ES invariant violations on
 * non-configurable properties of the real module). Reads delegate to the
 * real module; writes/defineProperty go into local overrides.
 */
const otOverrides: Record<string | symbol, any> = Object.create(null);

// Use a plain object as the proxy target so that invariant checks pass.
// The real module is only used as a fallback for reads.
export const OT: typeof OTClient = new Proxy({} as typeof OTClient, {
  get(_target, prop) {
    if (prop in otOverrides) {
      return otOverrides[prop];
    }
    return (OTClient as any)[prop];
  },
  set(_target, prop, value) {
    otOverrides[prop] = value;
    return true;
  },
  has(_target, prop) {
    return prop in otOverrides || prop in OTClient;
  },
  deleteProperty(_target, prop) {
    delete otOverrides[prop];
    return true;
  },
  defineProperty(_target, prop, descriptor) {
    // Jasmine's spyOn uses Object.defineProperty to install the spy
    if ('value' in descriptor) {
      otOverrides[prop] = descriptor.value;
    } else if ('get' in descriptor) {
      // Handle getter-based descriptors by creating a getter in overrides
      Object.defineProperty(otOverrides, prop as string, descriptor);
    }
    return true;
  },
  getOwnPropertyDescriptor(_target, prop) {
    if (prop in otOverrides) {
      return {
        value: otOverrides[prop],
        writable: true,
        configurable: true,
        enumerable: true,
      };
    }
    // Make the property appear writable/configurable so Jasmine's spyOn proceeds
    const val = (OTClient as any)[prop];
    if (val !== undefined || prop in OTClient) {
      return {
        value: val,
        writable: true,
        configurable: true,
        enumerable: true,
      };
    }
    return undefined;
  },
  ownKeys() {
    const keys = new Set<string | symbol>();
    // Get keys from the real module
    try {
      for (const key of Reflect.ownKeys(OTClient as any)) {
        keys.add(key);
      }
    } catch { /* ignore */ }
    // Add override keys
    for (const key of Object.keys(otOverrides)) {
      keys.add(key);
    }
    return Array.from(keys);
  },
}) as typeof OTClient;

/**
 * Configure the OT client SDK to point at the correct API server.
 * This must happen before any OT.initSession() calls.
 *
 * The SDK's internal StaticConfig reads from `window.OTProperties` (not
 * `OT.properties`) and filters for the key `apiURL` (uppercase "URL").
 * Setting `OT.properties.apiUrl` only updates a deprecated getter/setter
 * wrapper and does NOT redirect internal API calls.
 */
if (apiUrl) {
  // Primary mechanism: window.OTProperties is read by the SDK's StaticConfig
  // factory to override the built-in apiURL (https://anvil.opentok.com).
  (window as any).OTProperties = {
    ...((window as any).OTProperties || {}),
    apiURL: apiUrl,
  };

  // Also set the deprecated property for any code that reads it directly
  // (e.g. the logging server test that spreads OTClient.properties).
  (OTClient as any).properties.apiUrl = apiUrl;
}

/**
 * Creates a NetworkTest instance pre-configured for the current environment.
 * Pass additional options (audioOnly, timeout, etc.) as needed.
 *
 * Uses the mutable OT wrapper so that spyOn() replacements are actually
 * invoked during tests.
 */
export function createNetworkTest(
  sessionCredentials: SessionCredentials,
  options?: NetworkTestOptions,
): NetworkTest {
  return new NetworkTest(OT, sessionCredentials, options);
}
