name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: lib/js

    strategy:
      fail-fast: true
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Apply patch
        run: git apply ./opentok.patch

      - name: Linting
        run: npm run tslint

      - name: Testing
        run: npm run test

      - name: Build package
        run: npm run build

      - name: Publish to NPM
        run: npx changeset publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: compiled-package-dist
          path: lib/js/dist/
