name: Record Metrics

on:
  schedule:
    - cron: "0 0 * * *"

permissions: read-all

jobs:
  record-metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Record Metrics
        uses: michaeljolley/aggregit@v1
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          project_id: ${{ secrets.project_id }}
          private_key: ${{ secrets.private_key }}
          client_email: ${{ secrets.client_email }}
          firebaseDbUrl: ${{ secrets.firebaseDbUrl }}
